import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="about">Go To About Page</Link>
          </p>
          <div>
        Made By Hudson
          </div>
        </div>

        <div className={styles.center}>
        
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
            
          </div>
          <h2>Days Til Next Class</h2>
        </div>
        <h5>Computing Options:</h5>

        <div className={styles.grid}>
        {
          information && information.map((info, index) => {
            if(info.department === "Computing") {
            return(
              <Card key={index} degree={info.degree} colour="transparent" font="25px"/>
            )
            }
          })
        }  
       
        </div>
      </main>
    </>
  )
}
